### ISSUE TITLE
Cannot run tests on CI/CD Pipeline

### ISSUE THREAD

**Issue by FrenchMajesty** [adonisjs/adonis-framework#1173]
Hello,

I have tests cases and I tried to setup a pipeline on my Bitbucket repository so that every time a merge request is created, the pipeline runs the tests on the branch so that nothing broke.

When I open the console in my folder and run the command `adonis test` is goes successfully well but in the Docker environment it keeps failing with various errors. The latest one being that it cannot find an `.env` file

I have attached the pipeline logs here:

[pipelineLog-258.txt](https://github.com/adonisjs/adonis-framework/files/3907869/pipelineLog-258.txt)

## Package version
5.0.9

## Node.js and npm version
Node.js 10.15 and npm 6.9

## Sample Code (to reproduce the issue)
```
image: node:10.15.0

pipelines:
  pull-requests:
      '**':
        - step:
            name: Build and test
            script:
              - npm i -g @adonisjs/cli
              - npm i
              - adonis test
```
